In [10]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread ('/content/dog.jpeg')
print(img)
gray_img_max = np.max(img, axis = 2)
gray_img_min = np.min(img, axis = 2)
gray_img_01 = (gray_img_max + gray_img_min)/2
# print(gray_img_01)
gray_img_01 [0 , 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 61.1MB/s]
[[[118 134  71]
  [ 89 105  42]
  [ 82  98  35]
  ...
  [151 163 149]
  [151 163 149]
  [151 163 149]]

 [[119 135  72]
  [ 89 105  42]
  [ 83  99  36]
  ...
  [151 164 147]
  [151 163 149]
  [151 164 147]]

 [[119 135  72]
  [ 90 106  43]
  [ 83  99  36]
  ...
  [151 164 146]
  [150 163 146]
  [150 163 145]]

 ...

 [[145 155  94]
  [126 136  73]
  [119 132  62]
  ...
  [116 152  82]
  [113 149  79]
  [110 147  77]]

 [[138 148  87]
  [119 129  66]
  [112 125  56]
  ...
  [116 151  83]
  [113 148  80]
  [110 147  78]]

 [[136 146  85]
  [117 127  64]
  [109 122  53]
  ...
  [117 152  86]
  [114 149  83]
  [111 148  81]]]


102.5

In [11]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread ('/content/dog.jpeg')
print(img)
gray_img_01 = np.mean(img, axis = 2)

# print(gray_img_01)
gray_img_01 [0 , 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 51.3MB/s]
[[[118 134  71]
  [ 89 105  42]
  [ 82  98  35]
  ...
  [151 163 149]
  [151 163 149]
  [151 163 149]]

 [[119 135  72]
  [ 89 105  42]
  [ 83  99  36]
  ...
  [151 164 147]
  [151 163 149]
  [151 164 147]]

 [[119 135  72]
  [ 90 106  43]
  [ 83  99  36]
  ...
  [151 164 146]
  [150 163 146]
  [150 163 145]]

 ...

 [[145 155  94]
  [126 136  73]
  [119 132  62]
  ...
  [116 152  82]
  [113 149  79]
  [110 147  77]]

 [[138 148  87]
  [119 129  66]
  [112 125  56]
  ...
  [116 151  83]
  [113 148  80]
  [110 147  78]]

 [[136 146  85]
  [117 127  64]
  [109 122  53]
  ...
  [117 152  86]
  [114 149  83]
  [111 148  81]]]


107.66666666666667

In [12]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread ('/content/dog.jpeg')
print(img)
gray_img_R = img[:,:,0]
gray_img_G = img[:,:,1]
gray_img_B = img[:,:,2]
gray_img_01 = gray_img_R*0.21 + gray_img_G*0.72 + gray_img_B*0.07

# print(gray_img_01)
gray_img_01 [0 , 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 58.2MB/s]
[[[118 134  71]
  [ 89 105  42]
  [ 82  98  35]
  ...
  [151 163 149]
  [151 163 149]
  [151 163 149]]

 [[119 135  72]
  [ 89 105  42]
  [ 83  99  36]
  ...
  [151 164 147]
  [151 163 149]
  [151 164 147]]

 [[119 135  72]
  [ 90 106  43]
  [ 83  99  36]
  ...
  [151 164 146]
  [150 163 146]
  [150 163 145]]

 ...

 [[145 155  94]
  [126 136  73]
  [119 132  62]
  ...
  [116 152  82]
  [113 149  79]
  [110 147  77]]

 [[138 148  87]
  [119 129  66]
  [112 125  56]
  ...
  [116 151  83]
  [113 148  80]
  [110 147  78]]

 [[136 146  85]
  [117 127  64]
  [109 122  53]
  ...
  [117 152  86]
  [114 149  83]
  [111 148  81]]]


126.22999999999999

In [18]:
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('/content/advertising.csv')
data = df.to_numpy()
sale = data[:,3]
max_sale = np.max(sale)
index_max_sale = np.where(sale == max_sale)
print(max_sale, index_max_sale[0])

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 9.38MB/s]
27.0 [175]


In [19]:
mean_TV = np.mean(data[:,0])
print(mean_TV)

147.0425


In [24]:
print(sale[sale >= 20])

[22.1 22.4 24.4 20.5 20.9 21.4 25.4 21.5 20.7 23.2 22.6 21.2 20.2 23.7
 23.8 24.2 20.7 22.3 21.7 20.2 22.2 20.5 25.4 23.8 20.7 21.8 20.9 24.7
 20.8 20.7 20.1 25.4 20.6 20.  27.  20.2 26.2 22.6 20.9 25.5]


In [27]:
radio_condition = np.sum(sale[np.where(data[:,2] >= np.mean(data[:,2]))])
print(radio_condition)

1405.1


In [40]:
ss = np.where(sale == np.mean(sale), 'aven', (np.where(sale > np.mean(sale), 'good', 'bad')))
print(ss[7:10])

['bad' 'bad' 'good']


In [46]:
kk = abs(sale - np.mean(sale))
a = sale[np.where(kk == np.min(kk))]
print(a)
ss = np.where(sale == a, 'aven', (np.where(sale > a, 'good', 'bad')))
print(ss[7:10])

[15.2]
['bad' 'bad' 'good']
